import path from "node:path";
import { mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { createProjectFromIntent } from "../domain/topology-factory";
import { createArtifactBundle } from "../export/artifact-bundle";
import { validateExportManifest, withObservedPlannerResult } from "./export-manifest";
import { assertSafeProjectPath, writeProjectArtifacts } from "./project-writer";

describe("export manifest", () => {
  it("validates the MVP artifact manifest", () => {
    const bundle = createArtifactBundle(createProjectFromIntent("我需要4个交换机，每个交换机连接5个端系统"));

    expect(validateExportManifest(bundle)).toEqual({ ok: true });
  });

  it("records external planner output without requiring generated content", () => {
    const bundle = createArtifactBundle(createProjectFromIntent("我需要4个交换机，每个交换机连接5个端系统"));
    const manifest = withObservedPlannerResult(bundle.manifest);

    expect(manifest.files).toContainEqual({
      path: "flow_plan_result_1.json",
      purpose: "planner-output",
      label: "规划器输出",
      observedExternal: true,
    });
    expect(validateExportManifest({ ...bundle, manifest })).toEqual({ ok: true });
  });

  it("rejects planner output when it looks generated by the bundle", () => {
    const bundle = createArtifactBundle(createProjectFromIntent("我需要4个交换机，每个交换机连接5个端系统"));

    const validation = validateExportManifest({
      ...bundle,
      manifest: {
        ...bundle.manifest,
        files: [
          ...bundle.manifest.files,
          {
            path: "flow_plan_result_1.json",
            purpose: "planner-output",
            label: "规划器输出",
          },
        ],
      },
    });

    expect(validation).toMatchObject({ ok: false });
  });
});

describe("project writer", () => {
  it("writes artifacts without deleting unrelated files", async () => {
    const parentDir = await mkdtemp(path.join(tmpdir(), "tsn-agent-project-test-"));
    const outputDir = path.join(parentDir, "generated-project");
    const bundle = createArtifactBundle(createProjectFromIntent("我需要4个交换机，每个交换机连接5个端系统"));
    await mkdir(outputDir, { recursive: true });
    await writeFile(path.join(outputDir, "notes.txt"), "keep", "utf8");

    const result = await writeProjectArtifacts(outputDir, bundle, {
      repoRoot: process.cwd(),
      homeDir: path.join(parentDir, "home"),
    });

    expect(result.writtenFiles).toEqual([
      "tsnagent/generated/network.ned",
      "omnetpp.ini",
      "react-flow-topology.json",
      "flow_plan_1.json",
      "manifest.json",
    ]);
    expect(await readFile(path.join(outputDir, "notes.txt"), "utf8")).toBe("keep");
    expect(await readFile(path.join(outputDir, "tsnagent/generated/network.ned"), "utf8")).toContain("TsnSwitch");
    expect(await readFile(path.join(outputDir, "omnetpp.ini"), "utf8")).toContain(
      "network = tsnagent.generated.TsnAgentNetwork",
    );
    expect(await readFile(path.join(outputDir, "manifest.json"), "utf8")).toContain("simulation-inet");
  });

  it("rejects protected and unsafe output paths", async () => {
    const parentDir = await mkdtemp(path.join(tmpdir(), "tsn-agent-project-test-"));
    const homeDir = path.join(parentDir, "home");

    await expect(assertSafeProjectPath("relative/path")).rejects.toThrow("must be absolute");
    await expect(assertSafeProjectPath(process.cwd(), { repoRoot: process.cwd() })).rejects.toThrow("dangerous path");
    await expect(assertSafeProjectPath(homeDir, { homeDir })).rejects.toThrow("dangerous path");
    await expect(assertSafeProjectPath(path.join(homeDir, "TSN Project"), { homeDir })).resolves.toBe(
      path.join(homeDir, "TSN Project"),
    );
  });

  it("rejects symlink output paths", async () => {
    const parentDir = await mkdtemp(path.join(tmpdir(), "tsn-agent-project-test-"));
    const targetDir = path.join(parentDir, "target");
    const linkDir = path.join(parentDir, "link");
    await symlink(targetDir, linkDir);

    await expect(assertSafeProjectPath(linkDir)).rejects.toThrow("symlink");
  });
});
